version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/clojure:1.11.1
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/theikkila/clj-ulid/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          lein deps
          lein test
          

workflows:
  my-custom-workflow:
    jobs:
      - build